Repository google/trillian, pull requests merged in 2019-06, with the labels that each got.

#1647 GetLeavesByRevisionNoProofs API
  CHANGELOG.md
  docs/api.md
  integration/maptest/map.go
  server/map_rpc_server.go
  testonly/tmock/mock_map_server.go
  trillian_map_api.pb.go
  trillian_map_api.proto
Labels: cla: yes

#1651 Add missing calls to StorageProvider.Close()
  server/trillian_log_server/main.go
  server/trillian_map_server/main.go
Labels: cla: yes

#1568 TXRunner Interface
  merkle/sparse_merkle_tree.go
  merkle/sparse_merkle_tree_test.go
  server/map_rpc_server.go
Labels: cla: yes

#1652 Remove unused Snapshot interface
  storage/map_storage.go
  storage/mysql/map_storage_test.go
Labels: cla: yes

#1653 Introduce experimental package for Skylog
  skylog/README.md
Labels: cla: yes

#1655 New API service for writing to the Trillian Map
  CHANGELOG.md
  docs/api.md
  storage/mock_storage.go
  trillian_map_api.pb.go
  trillian_map_api.proto
Labels: cla: yes

#1654 skylog: Introduce tree storage interfaces
  skylog/storage/api.go
  skylog/storage/types.go
Labels: cla: yes

#1656 Add a log metric that counts non zero batches added by signers.
  log/operation_manager.go
Labels: cla: yes

#1659 Fix some typos and missing node id docs.
  storage/types.go
Labels: cla: yes

#1657 skylog: Add Cloud Spanner tree storage implementation
  skylog/storage/cloudspanner/schema.sdl
  skylog/storage/cloudspanner/tree.go
  skylog/storage/cloudspanner/tree_test.go
Labels: cla: yes

#1663 licenses tool: Parse flags that use "flag" package
  scripts/licenses/main.go
Labels: cla: yes

#1665 Use errgroup in VerifyMapLeavesResponse
  client/map_verifier.go
Labels: cla: yes

#1662 Improve formatting of errors in log output from `licenses csv`
  scripts/licenses/csv.go
Labels: cla: yes

#1668 Use go list to find certificate-transparency-go path
  .travis.yml
  integration/functions.sh
Labels: cla: yes

#1669 Upgrade to golangci-lint v1.17.0
  .travis.yml
  storage/postgres/log_storage.go
Labels: cla: yes

#1670 skylog: Fix unsupported types in schema and code
  skylog/storage/cloudspanner/schema.sdl
  skylog/storage/cloudspanner/tree.go
  skylog/storage/cloudspanner/tree_test.go
Labels: cla: yes

#1672 Fixed error message in crypto verifier.
  crypto/verifier.go
Labels: cla: yes

#1671 skylog: Add Merkle tree build worker
  skylog/core/builder.go
  skylog/core/builder_test.go
Labels: cla: yes

#1667 NodeID.SetRight
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1673 Scripts may not be executable, invoke with bash
  integration/functions.sh
Labels: cla: yes

#1658 Modify licenses tool to use "golang.org/x/tools/go/packages"
  scripts/licenses/README.md
  scripts/licenses/csv.go
  scripts/licenses/licenses/find.go
  scripts/licenses/licenses/find_test.go
  scripts/licenses/licenses/library.go
  scripts/licenses/licenses/library_test.go
  scripts/licenses/main.go
  scripts/licenses/save.go
Labels: cla: yes

#1678 Re-enable mockgen
  scripts/presubmit.sh
Labels: cla: yes

#1679 Add a first cut of the feature implementation matrix
  PULL_REQUEST_TEMPLATE.md
  README.md
  docs/Feature_Implementation_Matrix.md
Labels: cla: yes

#1686 Run CT Go tests with Go modules
  .travis.yml
Labels: cla: yes

#1684 Don't return LeafHash in RunGetLeafByRevisionNoProof
  integration/maptest/map.go
  server/map_rpc_server.go
Labels: cla: yes

#1683 Check for duplicates server side, not client side.
  client/map_client.go
  docs/api.md
  server/map_rpc_server.go
  testonly/hammer/hammer.go
  trillian_map_api.pb.go
  trillian_map_api.proto
Labels: cla: yes

#1688 Export GO111MODULE Variable in Docker Builds
  examples/deployment/docker-compose.yml
  examples/deployment/docker/log_server/Dockerfile
  examples/deployment/docker/log_signer/Dockerfile
  examples/deployment/docker/map_server/Dockerfile
Labels: cla: yes

#1689 Regenerate API files
  trillian_admin_api.pb.gw.go
  trillian_log_api.pb.gw.go
  trillian_map_api.pb.gw.go
Labels: cla: yes

#1680 skylog: Introduce sequence storage
  skylog/storage/api.go
  skylog/storage/cloudspanner/schema.sdl
  skylog/storage/cloudspanner/sequence.go
  skylog/storage/types.go
Labels: cla: yes

#1687 skylog: Add build worker based on Cloud Functions
  skylog/storage/cloudfunctions/go.mod
  skylog/storage/cloudfunctions/go.sum
  skylog/storage/cloudfunctions/worker.go
Labels: cla: yes

#1691 Add GOFLAGS environment variable to Dockerfiles
  CHANGELOG.md
  examples/deployment/docker/log_server/Dockerfile
  examples/deployment/docker/log_signer/Dockerfile
  examples/deployment/docker/map_server/Dockerfile
Labels: cla: yes

#1664 Remove toy map client
  examples/vmap/trillian_map_client/main.go
Labels: cla: yes

#1400 Enable Go Modules
  .travis.yml
  CHANGELOG.md
  README.md
  go.mod
  go.sum
  quota/etcd/quotapb/quotapb.pb.gw.go
  scripts/presubmit.sh
  tools.go
Labels: cla: yes

#1692 skylog: Create gcp storage folder
  skylog/storage/cloudfunctions/go.mod
  skylog/storage/cloudfunctions/go.sum
  skylog/storage/gcp/cloudfunc/go.mod
  skylog/storage/gcp/cloudfunc/go.sum
  skylog/storage/gcp/cloudfunc/worker.go
  skylog/storage/gcp/cloudspanner/schema.sdl
  skylog/storage/gcp/cloudspanner/sequence.go
  skylog/storage/gcp/cloudspanner/tree.go
  skylog/storage/gcp/cloudspanner/tree_test.go
Labels: cla: yes

#1696 skylog: Update dependency from the renamed package
  skylog/storage/gcp/cloudfunc/go.mod
  skylog/storage/gcp/cloudfunc/go.sum
  skylog/storage/gcp/cloudfunc/worker.go
Labels: cla: yes

#1694 Remove vendor exclusion from codecov.yml
  codecov.yml
Labels: cla: yes

#1698 Remove reference to vendor dir from presubmit
  scripts/presubmit.sh
Labels: cla: yes

#1676 Implementation of Map Write API that delegates to legacy methods.
  integration/map.go
  integration/map_integration_test.go
  integration/maptest/map.go
  integration/maptest/map_test.go
  server/map_write_rpc_server.go
  server/trillian_map_server/main.go
  testonly/integration/mapenv.go
Labels: cla: yes

#1697 skylog: Add GCP proto package
  skylog/storage/gcp/gcppb/gcp.pb.go
  skylog/storage/gcp/gcppb/gcp.proto
  skylog/storage/gcp/gcppb/gen.go
Labels: cla: yes

#1700 skylog: Use protobuf in workers instead of JSON
  skylog/storage/gcp/cloudfunc/go.mod
  skylog/storage/gcp/cloudfunc/go.sum
  skylog/storage/gcp/cloudfunc/worker.go
Labels: cla: yes

#1701 skylog: Add binary for testing BuildJob publishing
  go.mod
  skylog/storage/gcp/pubsub/main.go
Labels: cla: yes

#1704 Use *trillian.MapLeaf in mapTX.Set
  server/map_rpc_server.go
  storage/cloudspanner/map_storage.go
  storage/map_storage.go
  storage/mock_storage.go
  storage/mysql/map_storage.go
  storage/mysql/map_storage_test.go
Labels: cla: yes

#1695 Correct use of pathspec magic
  .travis.yml
Labels: cla: yes

#1699 In quota tests don't copy proto buffer contents
  quota/etcd/etcdqm/etcdqm_test.go
  quota/etcd/storage/quota_storage_test.go
Labels: cla: yes

#1682 Add a MapWriteStress test
  examples/deployment/docker/db_server/mysql.cnf
  integration/maptest/map.go
  integration/maptest/map_test.go
Labels: cla: yes

#1708 Fix the build
  integration/maptest/map.go
Labels: cla: yes

#1702 Use a function to unmarshal MapLeaf
  storage/mysql/map_storage.go
Labels: cla: yes

#1707 Remove unused newNodeIDFromBigIntOld
  storage/node.go
  storage/node_test.go
Labels: cla: yes

#1705 NewEmptyNodeID return *trillian.MapLeaf
  merkle/sparse_merkle_tree.go
  merkle/sparse_merkle_tree_test.go
  server/map_rpc_server.go
  server/proof_fetcher_test.go
  storage/cache/subtree_cache_test.go
  storage/memory/tree_debug.go
  storage/memory/tree_storage.go
  storage/node.go
  storage/node_test.go
Labels: cla: yes

#1703 skylog: Add tree sharding description to job messages
  skylog/storage/gcp/gcppb/gcp.pb.go
  skylog/storage/gcp/gcppb/gcp.proto
  skylog/storage/gcp/pubsub/main.go
Labels: cla: yes

#1706 Fix a couple of reflection based comparisons on protos in tests
  server/log_rpc_server_test.go
  storage/admin_helpers_test.go
Labels: cla: yes

#1710 skylog: Fixup flags in the build jobs sending tool
  skylog/storage/gcp/pubsub/main.go
Labels: cla: yes

#1715 Pass `trillian.SignedMapRoot` by reference
  server/map_rpc_server.go
  server/map_rpc_server_test.go
  storage/cloudspanner/map_storage.go
  storage/map_storage.go
  storage/mock_storage.go
  storage/mysql/map_storage.go
  storage/mysql/map_storage_test.go
Labels: cla: yes

#1713 skylog: Add sequence storage sharding info to jobs
  skylog/storage/gcp/gcppb/gcp.pb.go
  skylog/storage/gcp/gcppb/gcp.proto
  skylog/storage/gcp/pubsub/main.go
Labels: cla: yes

#1716 Raise lint timeout from 5 to 8 minutes.
  scripts/presubmit.sh
Labels: cla: yes

#1721 Cloud Build should use latest images as cache when building new images
  cloudbuild_master.yaml
Labels: cla: yes, enhancement

#1714 Extracted map root verification out of client packages.
  client/map_verifier.go
  maps/root_verifier.go
  server/map_write_rpc_server.go
Labels: cla: yes

#1723 Turn on go modules in cloud build
  cloudbuild.yaml
  cloudbuild_master.yaml
  cloudbuild_tag.yaml
Labels: cla: yes

#1725 Set cloudbuild timeout to 15m
  cloudbuild.yaml
  cloudbuild_master.yaml
  cloudbuild_tag.yaml
Labels: cla: yes

#1727 Pass context to storeSubtrees()
  CHANGELOG.md
  log/operation_manager.go
  log/operation_manager_test.go
  log/sequencer_manager_test.go
  log/sequencer_test.go
  merkle/sparse_merkle_tree_test.go
  server/log_rpc_server.go
  server/log_rpc_server_test.go
  server/map_rpc_server.go
  server/map_rpc_server_test.go
  storage/cache/gen.go
  storage/cache/mock_node_storage.go
  storage/cache/subtree_cache.go
  storage/cache/subtree_cache_test.go
  storage/cloudspanner/log_storage.go
  storage/cloudspanner/map_storage.go
  storage/cloudspanner/tree_storage.go
  storage/log_storage.go
  storage/memory/log_storage.go
  storage/memory/tree_storage.go
  storage/mock_storage.go
  storage/mysql/log_storage.go
  storage/mysql/log_storage_test.go
  storage/mysql/map_storage.go
  storage/mysql/map_storage_test.go
  storage/mysql/tree_storage.go
  storage/postgres/log_storage.go
  storage/postgres/log_storage_test.go
  storage/postgres/tree_storage.go
  storage/testonly/transaction.go
  storage/tools/dump_tree/dumplib/dumplib.go
  storage/tree_storage.go
Labels: cla: yes

#1719 Update prometheus-to-sd from v0.3.2 to v0.5.2
  examples/deployment/kubernetes/trillian-log-deployment.yaml
  examples/deployment/kubernetes/trillian-log-signer-deployment.yaml
  examples/deployment/kubernetes/trillian-map-deployment.yaml
Labels: cla: yes

#1718 Remove etcd-service.yaml
  examples/deployment/kubernetes/create.sh
  examples/deployment/kubernetes/etcd-service.yaml
Labels: cla: yes, cleanup

#1720 Address TODOs by using `kubectl wait`
  examples/deployment/kubernetes/create.sh
Labels: cla: yes, enhancement

#1711 skylog: Get tree sharding info from BuildJob
  skylog/storage/gcp/cloudfunc/go.mod
  skylog/storage/gcp/cloudfunc/go.sum
  skylog/storage/gcp/cloudfunc/worker.go
Labels: cla: yes

#1728 Storage test helpers accept storage interfaces
  storage/mysql/log_storage_test.go
  storage/mysql/map_storage_test.go
  storage/mysql/storage_test.go
Labels: cla: yes, tests

#1729 Remove unused Snapshot function
  storage/cloudspanner/map_storage.go
  storage/mysql/map_storage.go
Labels: cla: yes

#1722 Make namespace configurable in Kubernetes configs
  examples/deployment/kubernetes/create.sh
  examples/deployment/kubernetes/deploy.sh
  examples/deployment/kubernetes/etcd-role-binding.yaml
  examples/deployment/kubernetes/etcd-role.yaml
  examples/deployment/kubernetes/trillian-cloudspanner.yaml
  examples/deployment/kubernetes/trillian-mysql.yaml
  examples/deployment/kubernetes/trillian-opensource-ci-config.sh
  examples/deployment/kubernetes/trillian-opensource-ci.yaml
Labels: cla: yes, enhancement

#1732 Added interceptor for Map WriteLeaves added in #1655.
  .golangci.yaml
  server/interceptor/interceptor.go
  server/interceptor/interceptor_test.go
Labels: cla: yes

#1731 Remove GO111MODULE build arg from Cloud Build configs
  cloudbuild.yaml
  cloudbuild_master.yaml
  cloudbuild_tag.yaml
Labels: cla: yes

#1736 Fix incorrect usages of quota related protos
  quota/etcd/quotaapi/conversions_test.go
  quota/etcd/quotaapi/quota_server_test.go
  quota/etcd/storage/quota_storage.go
Labels: cla: yes

#1737 Stop removing ConfigMaps when deploying Trillian on Kubernetes
  cloudbuild_master.yaml
Labels: cla: yes

#1742 Update build instructions in README
  README.md
Labels: cla: yes

#1743 Fix nits I missed
  README.md
Labels: cla: yes

#1744 Enable goproxy in travis
  .travis.yml
Labels: cla: yes
