Repository google/trillian, pull requests merged in 2019-08, with the labels that each got.

#1785 Update a couple of broken deps
  WORKSPACE
  go.mod
  go.sum
Labels: cla: yes, cleanup

#1788 Create patch release v1.3.1
  CHANGELOG.md
  WORKSPACE
  go.mod
  go.sum
Labels: cla: yes

#1784 Ensure MapHammer deadline errors are propagated
  testonly/hammer/hammer.go
  testonly/hammer/hammer_test.go
  testonly/hammer/maphammer/main.go
Labels: bug, cla: yes, tests

#1790 Replace whole operation timeout with per-rpc timeout
  client/timeout/timeout.go
  testonly/hammer/hammer.go
  testonly/hammer/maphammer/main.go
Labels: cla: yes

#1781 Update CHANGELOG for v1.3.0
  CHANGELOG.md
Labels: cla: yes

#1792 Remove tracing for recursive subtree calls.
  merkle/sparse_merkle_tree.go
Labels: cla: yes
