Repository google/trillian, pull requests merged in 2019-07, with the labels that each got.

#1739 Remove reference to etcd-service.yaml from kubernetes/create.sh
  examples/deployment/kubernetes/create.sh
Labels: cla: yes

#1745 Increase Cloud Build timeout from 15 mins to 20 mins
  cloudbuild.yaml
  cloudbuild_master.yaml
  cloudbuild_tag.yaml
Labels: cla: yes

#1734 Fix cases where trillian.Tree protos were being incorrectly passed by value.
  client/log_client_test.go
  client/map_client_test.go
  cmd/createtree/main_test.go
  cmd/createtree/pem_test.go
  integration/admin/admin_integration_test.go
  server/admin/admin_server_test.go
  server/interceptor/interceptor_test.go
  server/map_rpc_server_test.go
  storage/cloudspanner/admin.go
  storage/memory/admin_storage.go
  storage/memory/tree_storage.go
  storage/mysql/admin_storage.go
  storage/mysql/admin_storage_test.go
  storage/mysql/log_storage_test.go
  storage/postgres/admin_storage.go
  storage/postgres/admin_storage_test.go
  storage/postgres/log_storage_test.go
  storage/testonly/admin_storage_tester.go
  storage/tree_validation_test.go
  trees/trees_test.go
Labels: cla: yes

#1735 Fix storage API Get / Set root passing SignedLogRoot proto by value
  CHANGELOG.md
  log/sequencer.go
  log/sequencer_manager_test.go
  log/sequencer_test.go
  quota/mysqlqm/mysql_quota_test.go
  server/log_rpc_server.go
  server/log_rpc_server_test.go
  storage/cloudspanner/log_storage.go
  storage/log_storage.go
  storage/memory/log_storage.go
  storage/mock_storage.go
  storage/mysql/log_storage.go
  storage/mysql/log_storage_test.go
  storage/mysql/storage_test.go
  storage/postgres/log_storage.go
  storage/postgres/log_storage_test.go
  storage/postgres/storage_test.go
  storage/tools/dump_tree/dumplib/dumplib.go
Labels: cla: yes

#1748 Fix incorrect copying / other usages of trillian log api protos.
  server/log_rpc_server.go
  server/log_rpc_server_test.go
  server/proof_fetcher.go
  server/proof_fetcher_test.go
Labels: cla: yes

#1733 Use Kaniko cache to accelerate Docker builds in Cloud Build
  cloudbuild.yaml
  cloudbuild_master.yaml
  cloudbuild_tag.yaml
Labels: cla: yes

#1746 Try to clean up test DBs after use
  integration/admin/admin_integration_test.go
  integration/quota/quota_test.go
  quota/mysqlqm/mysql_quota_test.go
  storage/mysql/admin_storage_test.go
  storage/mysql/storage_test.go
  storage/postgres/storage_test.go
  storage/postgres/testdb/testdb.go
  storage/testdb/testdb.go
  testonly/integration/logenv.go
  testonly/integration/mapenv.go
  testonly/integration/registry.go
Labels: cla: yes, enhancement

#1749 Correct name of build steps in cloudbuild_master.yaml
  cloudbuild_master.yaml
Labels: bug, cla: yes

#1724 MapStorage Integration Tests
  integration/storagetest/maphelpers.go
  integration/storagetest/maptestrunner.go
  integration/storagetest/maptests.go
  integration/storagetest/treehelpers.go
  storage/cloudspanner/map_storage_test.go
  storage/mysql/map_storage_test.go
Labels: cla: yes, tests

#1752 Avoid potential SEGV in sequencer if log is not initialised
  storage/mysql/log_storage.go
  storage/mysql/log_storage_test.go
Labels: bug, cla: yes, cleanup

#1750 Fix MySQL DROP
  storage/testdb/testdb.go
Labels: cla: yes

#1753 Don't install test deps each time
  scripts/presubmit.sh
Labels: cla: yes, cleanup

#1751 Increase Cloud Build timeout from 20 minutes to 30 minutes
  cloudbuild.yaml
  cloudbuild_master.yaml
  cloudbuild_tag.yaml
Labels: cla: yes

#1759 Fix various go module related unhappiness
  .travis.yml
  go.mod
  go.sum
Labels: cla: yes

#1761 merkle: Helper to get node IDs of a compact range
  log/sequencer.go
  merkle/compact/nodes.go
  merkle/compact/nodes_test.go
  merkle/compact/range_test.go
Labels: cla: yes

#1762 Export compact range decomposition helper
  merkle/compact/nodes.go
  merkle/compact/range.go
  merkle/compact/range_test.go
Labels: cla: yes

#1758 Another bunch of assorted lint fixes.
  integration/storagetest/maptests.go
  merkle/log_verifier_test.go
  merkle/memory_merkle_tree.go
  merkle/sparse_merkle_tree.go
  server/map_rpc_server.go
  storage/postgres/log_storage.go
  storage/testonly/matchers.go
  testonly/hammer/hammer.go
  testonly/mapcontents.go
  testonly/matchers/proto.go
  util/election/runner_test.go
Labels: cla: yes

#1760 Another bunch of fixes, this time for unhandled errors.
  merkle/compact/range_test.go
  monitoring/prometheus/etcdiscover/main.go
  server/cloudspanner_storage_provider.go
  server/quota_test.go
  server/trillian_map_server/main.go
  testonly/hammer/mapreplay/main.go
  testonly/hammer/replay.go
  testonly/hammer/replay_test.go
Labels: cla: yes

#1650 Ensure that TreeID is part of the MySQL join condition.
  storage/mysql/tree_storage.go
Labels: cla: yes

#1755 Fix a bunch of lint errors.
  crypto/keys/testonly/keys.go
  integration/maptest/map.go
  quota/etcd/etcdqm/etcdqm.go
  scripts/licenses/csv.go
  scripts/licenses/licenses/git.go
  scripts/licenses/save.go
  server/map_rpc_server.go
  skylog/storage/gcp/cloudspanner/sequence.go
  storage/postgres/queue.go
  storage/postgres/testdb/testdb.go
  storage/postgres/tree_storage.go
  storage/testonly/admin_storage_tester.go
Labels: cla: yes

#1765 Avoid SEGV if there is no latest STH
  log/sequencer.go
Labels: cla: yes

#1754 Separate lint tests out into their own travis env
  .travis.yml
Labels: cla: yes, tests

#1766 Split CT integration test out in Travis matrix
  .travis.yml
Labels: cla: yes, tests

#1767 Add go-cache to the travis cache
  .travis.yml
Labels: cla: yes, tests

#1769 Fix opencensus deprecation of DefaultServerViews.
  monitoring/opencensus/trace.go
Labels: cla: yes

#1763 Do not schedule multiple Etcd nodes on a single machine
  examples/deployment/kubernetes/etcd-cluster.yaml
Labels: cla: yes

#1773 Stop Istio injecting sidecar into Etcd nodes
  examples/deployment/kubernetes/etcd-cluster.yaml
Labels: cla: yes

#1774 Add t.Run() call to TestGitFileURL
  scripts/licenses/licenses/git_test.go
Labels: cla: yes, tests

#1779 docs: fix typo
  README.md
Labels: cla: yes

#1770 Mark some longer-running tests as parallel ok
  crypto/keys/der/der_test.go
  crypto/keys/generate_test.go
  merkle/hstar2_test.go
  scripts/licenses/licenses/git_test.go
  scripts/presubmit.sh
  util/clock/time_test.go
Labels: cla: yes, tests

#1780 Release v1.3.0
  CHANGELOG.md
Labels: cla: yes

#1777 Rename trillian-opensource-ci.* to trillian-ci-spanner.*
  cloudbuild_master.yaml
  examples/deployment/kubernetes/trillian-ci-spanner-config.sh
  examples/deployment/kubernetes/trillian-ci-spanner.yaml
Labels: cla: yes, tests

#1776 Always deploy etcd-operator to default namespace
  examples/deployment/kubernetes/etcd-deployment.yaml
  examples/deployment/kubernetes/etcd-role-binding.yaml
Labels: cla: yes

#1778 Move STORAGE_FLAG into Kubernetes secret
  examples/deployment/kubernetes/trillian-cloudspanner.yaml
  examples/deployment/kubernetes/trillian-log-deployment.yaml
  examples/deployment/kubernetes/trillian-log-signer-deployment.yaml
  examples/deployment/kubernetes/trillian-map-deployment.yaml
Labels: cla: yes, security
