Repository google/trillian, pull requests merged in 2019-05, with the labels that each got.

#1552 Add optional CPU and heap profiling to the three main trillian binaries.
  CHANGELOG.md
  server/trillian_log_server/main.go
  server/trillian_log_signer/main.go
  server/trillian_map_server/main.go
Labels: cla: yes

#1553 CODEOWNERS: only apply to top-level API protos
  CODEOWNERS
Labels: cla: yes

#1551 Workaround for single-tx-mode map performance issues
  CHANGELOG.md
  server/map_rpc_server.go
  server/trillian_map_server/main.go
Labels: cla: yes

#1555 Travis mania
  .travis.yml
Labels: cla: yes

#1550 sequencer: Clean up compact Tree updates
  log/sequencer.go
Labels: cla: yes

#1556 Remove unused hash mismatch type
  merkle/compact/tree.go
  merkle/compact/tree_test.go
Labels: cla: yes

#1558 Fix the bug which made the map go-faster change go slower.
  server/map_rpc_server.go
  server/trillian_map_server/main.go
Labels: cla: yes

#1527 Prototool linter support
  .travis.yml
  README.md
  prototool.yaml
  scripts/presubmit.sh
Labels: cla: yes

#1560 Simplify range_test
  merkle/compact/range_test.go
Labels: cla: yes

#1557 Faster version of NodeID.String() for use by sparse_merkle_tree
  merkle/sparse_merkle_tree.go
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1559 Do preload nodeID calculations in parallel
  server/map_rpc_server.go
Labels: cla: yes

#1561 compact: Report ephemeral nodes through visitor
  merkle/compact/range.go
  merkle/compact/range_test.go
Labels: cla: yes

#1564 Clarified documentation for important NodeID methods.
  storage/types.go
Labels: cla: yes

#1562 Add a bunch of tracing spans in sparse Merkle writer
  merkle/sparse_merkle_tree.go
  merkle/sparse_merkle_tree_test.go
  server/map_rpc_server.go
Labels: cla: yes

#1569 compact: Reuse visitor function definition
  integration/log.go
  log/sequencer.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
  storage/cache/log_subtree_cache.go
  storage/cache/subtree_cache_test.go
  storage/mysql/storage_test.go
  storage/testonly/fake_node_reader.go
Labels: cla: yes

#1572 compact: Move NodeID and clean up comments
  merkle/compact/range.go
  merkle/compact/tree.go
Labels: cla: yes

#1573 compact: Use NodeID in visitor signature
  integration/log.go
  log/sequencer.go
  merkle/compact/range.go
  merkle/compact/range_test.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
  storage/cache/log_subtree_cache.go
  storage/cache/subtree_cache_test.go
  storage/mysql/storage_test.go
  storage/testonly/fake_node_reader.go
Labels: cla: yes

#1574 Require Docker tests to pass for Travis build to succeed
  .travis.yml
Labels: cla: yes

#1566 Fetch leaves and their inclusion proofs concurrently
  server/map_rpc_server.go
Labels: cla: yes

#1576 Add tracing abstraction, and opencensus impl
  merkle/sparse_merkle_tree.go
  monitoring/opencensus/trace.go
  monitoring/rpc_stats_interceptor.go
  monitoring/trace.go
  server/interceptor/interceptor.go
  server/log_rpc_server.go
  server/map_rpc_server.go
  server/proof_fetcher.go
  server/trillian_log_server/main.go
  server/trillian_log_signer/main.go
  server/trillian_map_server/main.go
  storage/admin_helpers.go
  trees/trees.go
Labels: cla: yes

#1577 Add setter/getter for span func
  monitoring/trace.go
  server/trillian_log_server/main.go
  server/trillian_log_signer/main.go
  server/trillian_map_server/main.go
Labels: cla: yes

#1579 Add map leaves read/written metrics
  server/map_rpc_server.go
Labels: cla: yes

#1578 Make trace spans more readable
  monitoring/rpc_stats_interceptor.go
  server/interceptor/interceptor.go
  server/log_rpc_server.go
  storage/admin_helpers.go
  trees/trees.go
Labels: cla: yes

#1580 compact: Remove leaf index from method signatures
  integration/log.go
  log/sequencer.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
  storage/cache/log_subtree_cache.go
  storage/cache/subtree_cache_test.go
  storage/mysql/storage_test.go
Labels: cla: yes

#1575 CONIKS, hstar2 and SMT Writer performance improvements
  merkle/coniks/coniks.go
  merkle/coniks/coniks_test.go
  merkle/hstar2.go
  merkle/hstar2_test.go
  merkle/sparse_merkle_tree.go
  storage/cache/map_subtree_cache.go
Labels: cla: yes

#1583 sequencer: Remove redundant hashmap update
  log/sequencer.go
Labels: cla: yes

#1531 Add licenses, copyright notices and code to Docker images
  .gitignore
  examples/deployment/docker/log_server/Dockerfile
  examples/deployment/docker/log_signer/Dockerfile
  examples/deployment/docker/map_server/Dockerfile
  scripts/licenses/csv.go
  scripts/licenses/licenses/classifier.go
  scripts/licenses/licenses/classifier_test.go
  scripts/licenses/licenses/find.go
  scripts/licenses/licenses/find_test.go
  scripts/licenses/licenses/git.go
  scripts/licenses/licenses/git_test.go
  scripts/licenses/licenses/library.go
  scripts/licenses/licenses/library_test.go
  scripts/licenses/licenses/testdata/LICENSE
  scripts/licenses/licenses/testdata/direct/LICENSE
  scripts/licenses/licenses/testdata/direct/direct.go
  scripts/licenses/licenses/testdata/direct/subpkg/subpkg.go
  scripts/licenses/licenses/testdata/indirect/LICENSE
  scripts/licenses/licenses/testdata/indirect/external.go
  scripts/licenses/licenses/testdata/internal/internal.go
  scripts/licenses/licenses/testdata/testdata.go
  scripts/licenses/main.go
  scripts/licenses/save.go
Labels: cla: yes

#1361 Require docker-compose v3.1 or higher
  CHANGELOG.md
  examples/deployment/docker-compose.yml
Labels: cla: yes

#1542 Postgres tests should not fail if a Postgres server is not available
  storage/mysql/storage_test.go
  storage/postgres/storage_test.go
Labels: cla: yes

#1320 Refactor log_operation_manager_test.go
  server/log_operation_manager_test.go
Labels: cla: yes

#1581 compact.Tree: Handle root hash recalculation error
  merkle/compact/tree.go
Labels: cla: yes

#1585 sequencer: Factor out quota replenishment
  log/sequencer.go
Labels: cla: yes

#1582 compact.Tree: Compute root hash on demand
  integration/log.go
  log/sequencer.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
  storage/cache/log_subtree_cache.go
  storage/cache/subtree_cache_test.go
  storage/testonly/fake_node_reader.go
Labels: cla: yes

#1588 License tool includes the target Go package in its output
  scripts/licenses/licenses/library.go
  scripts/licenses/licenses/library_test.go
Labels: cla: yes

#1586 Shorten trace names in sparse merkle writer
  merkle/sparse_merkle_tree.go
Labels: cla: yes

#1589 Populate subtrees concurrently
  storage/cache/subtree_cache.go
Labels: cla: yes

#1590 log_subtree_cache: Factor out visitor callback
  storage/cache/log_subtree_cache.go
  storage/cache/subtree_cache_test.go
Labels: cla: yes

#1597 Sort and merge `go get/install` commands in .travis.yml
  .travis.yml
Labels: cla: yes, cleanup

#1595 Add timeout to sequencing context
  CHANGELOG.md
  server/log_operation_manager.go
Labels: cla: yes

#1599 compact.Tree: Allow nil visitor and add benchmarks
  integration/log.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
Labels: cla: yes

#1600 Correct name of "licenses" binary in .gitignore
  .gitignore
Labels: cla: yes

#1596 Delete Dockerfile.db
  CHANGELOG.md
  Dockerfile.db
Labels: cla: yes, cleanup

#1601 Switch some low-level logging in hashing related code to 'if' guards
  merkle/coniks/coniks.go
  merkle/maphasher/maphasher.go
  merkle/sparse_merkle_tree.go
  storage/cache/subtree_cache.go
  storage/types.go
Labels: cla: yes

#1602 Just one copy of bytes from big.Int in NewNodeIDFromBigInt
  storage/types.go
Labels: cla: yes

#1606 Remove update_changelog.sh
  scripts/update_changelog.sh
Labels: cla: yes, cleanup

#1608 LogHasher: Return no error from HashLeaf method
  client/log_client.go
  client/log_verifier.go
  integration/log.go
  log/sequencer_test.go
  merkle/compact/range_test.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
  merkle/hashers/tree_hasher.go
  merkle/log_verifier_test.go
  merkle/memory_merkle_tree.go
  merkle/memory_merkle_tree_test.go
  merkle/rfc6962/rfc6962.go
  merkle/rfc6962/rfc6962_test.go
  server/log_rpc_server.go
  server/log_rpc_server_test.go
  server/proof_fetcher_test.go
  server/sequencer_manager_test.go
  storage/cache/subtree_cache_test.go
  storage/tools/hasher/main.go
Labels: cla: yes

#1609 log_subtree_cache: Use compact Range instead of Tree
  storage/cache/log_subtree_cache.go
  storage/cache/subtree_cache_test.go
Labels: cla: yes

#1610 Improve FlipRightBit by doing it directly.
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1611 MapHasher: Do not return error from HashLeaf
  integration/map.go
  integration/maptest/map.go
  merkle/coniks/coniks.go
  merkle/coniks/coniks_test.go
  merkle/hashers/tree_hasher.go
  merkle/hstar2_test.go
  merkle/map_verifier.go
  merkle/maphasher/maphasher.go
  merkle/maphasher/maphasher_test.go
  merkle/sparse_merkle_tree_test.go
  server/map_rpc_server.go
  testonly/mapcontents.go
Labels: cla: yes

#1592 compact.Tree: Change semantic of adding leaves
  CHANGELOG.md
  integration/log.go
  log/sequencer.go
  merkle/compact/range_test.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
  storage/mysql/storage_test.go
  storage/testonly/fake_node_reader.go
Labels: cla: yes

#1613 Couple of changes to make NodeIDs more frugal.
  storage/cache/log_subtree_cache.go
  storage/cache/map_subtree_cache.go
  storage/suffix.go
  storage/suffix_test.go
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1614 Convert directly from Int.Bits() to NodeID
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1612 Make MaskLeft of NodeID return an explicit copy.
  merkle/map_verifier.go
  storage/types.go
Labels: cla: yes

#1604 Guard verbose logging in merkle path code
  merkle/merkle_path.go
Labels: cla: yes

#1522 compact: Implement Tree using Range
  merkle/compact/tree.go
  merkle/compact/tree_test.go
Labels: cla: yes

#1618 compact: Simplify getting hashes in NewTreeWithState
  log/sequencer.go
  log/sequencer_test.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
Labels: cla: yes

#1620 merkle: Add testonly package with golden hashes
  merkle/compact/tree_test.go
  merkle/testonly/constants.go
  testonly/compact_merkle_tree.go
Labels: cla: yes

#1616 Mention protoc-gen-doc in README.md
  README.md
Labels: cla: yes, docs

#1621 Remove old hash list format from compact.Tree
  merkle/compact/tree.go
  merkle/compact/tree_test.go
  merkle/testonly/constants.go
Labels: cla: yes

#1622 Clean up compact.Tree tests
  merkle/compact/tree.go
  merkle/compact/tree_test.go
Labels: cla: yes

#1627 Fix bazel build
  BUILD.bazel
  WORKSPACE
Labels: cla: yes

#1625 Remove unused NodeReader method
  storage/mysql/tree_storage.go
  storage/testonly/fake_node_reader.go
Labels: cla: yes

#1629 sequencer: Consolidate compact.Tree initialization
  log/sequencer.go
Labels: cla: yes

#1630 Remove redundant root hash calculations
  log/sequencer.go
  storage/testonly/fake_node_reader.go
Labels: cla: yes

#1615 Parallelize VerifyMapLeavesResponse
  client/map_verifier.go
Labels: cla: yes

#1631 fake_node_reader: Remove unused field
  storage/testonly/fake_node_reader.go
Labels: cla: yes

#1632 Complete TODO
  log/sequencer.go
Labels: cla: yes

#1628 Use uint64 throughout compact.Tree
  log/sequencer.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
Labels: cla: yes

#1623 GetMapLeafByRevision API
  CHANGELOG.md
  docs/api.md
  integration/map.go
  server/interceptor/interceptor.go
  server/map_rpc_server.go
  server/mock_log_operation.go
  testonly/tmock/mock_map_server.go
  trillian_map_api.pb.go
  trillian_map_api.proto
Labels: cla: yes

#1510 sequencer: Use compact.Range directly
  log/sequencer.go
  log/sequencer_test.go
Labels: cla: yes

#1634 compact: Move node utils to a separate file
  merkle/compact/nodes.go
  merkle/compact/range.go
  merkle/compact/tree.go
Labels: cla: yes

#1633 Remove all usages of compact.Tree
  integration/log.go
  storage/mysql/storage_test.go
  storage/testonly/fake_node_reader.go
Labels: cla: yes

#1635 Update codecov config. Remove regexes for top level folders.
  codecov.yml
Labels: cla: yes

#1636 Add methods for individually getting at prefix/suffix of NodeID
  storage/cache/subtree_cache.go
  storage/cache/subtree_cache_test.go
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1638 Move TreeNodes tests to a separate file
  merkle/compact/nodes_test.go
  merkle/compact/tree_test.go
Labels: cla: yes

#1637 Remove compact.Tree
  CHANGELOG.md
  merkle/compact/range.go
  merkle/compact/range_test.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
Labels: cla: yes

#1619 Remove FlipRightBit and fold into Neighbor func.
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1641 Regenerate api with latest version of grpc-gateway.
  trillian_log_api.pb.gw.go
Labels: cla: yes

#1639 Rename TreeNodes to RangeNodesForPrefix
  log/sequencer.go
  merkle/compact/nodes.go
  merkle/compact/nodes_test.go
  merkle/compact/range_test.go
Labels: cla: yes

#1643 Move log operation code to log package
  log/gen.go
  log/mock_operation.go
  log/operation_manager.go
  log/operation_manager_test.go
  log/sequencer.go
  log/sequencer_manager.go
  log/sequencer_manager_test.go
  log/sequencer_test.go
  server/log_rpc_server_test.go
  server/main.go
  server/mock_log_operation.go
  server/trillian_log_signer/main.go
  testonly/integration/logenv.go
Labels: cla: yes

#1645 log: Fix linter complaints
  log/gen.go
  log/mock_operation.go
  log/operation_manager.go
Labels: cla: yes

#1644 Remove unused interface method
  log/mock_operation.go
  log/operation_manager.go
  log/sequencer_manager.go
Labels: cla: yes

#1646 log: Delete unnecessary mutex
  log/operation_manager.go
Labels: cla: yes

#1642 Fold the MaskLeft operation into Neighbour.
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1617 Remove NewNodeIDWithPrefix constructor.
  storage/mysql/storage_test.go
  storage/postgres/storage_test.go
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1526 GetLatestInRange Map API
  docs/api.md
  quota/etcd/quotapb/quotapb.pb.gw.go
  server/map_rpc_server.go
  testonly/tmock/mock_map_server.go
  trillian_map_api.pb.go
  trillian_map_api.pb.gw.go
  trillian_map_api.proto
Labels: cla: yes

#1648 Add mhutchinson to CODEOWNERS for map api
  CODEOWNERS
Labels: cla: yes

#1649 Use []*trillian.MapLeaf consistently
  log/mock_operation.go
  server/map_rpc_server.go
  storage/cloudspanner/map_storage.go
  storage/map_storage.go
  storage/mock_storage.go
  storage/mysql/map_storage.go
  storage/mysql/map_storage_test.go
Labels: cla: yes
