Repository google/trillian, pull requests merged in 2019-04, with the labels that each got.

#1489 Unmarshal tree info in readTrees
  storage/cloudspanner/admin.go
Labels: cla: yes

#1480 Fixes for transaction leaks in RPC server and storage level operations
  CHANGELOG.md
  server/log_rpc_server.go
  server/log_rpc_server_test.go
  server/map_rpc_server.go
  server/map_rpc_server_test.go
  storage/memory/log_storage.go
  storage/mysql/log_storage.go
Labels: bug, cla: yes, cleanup

#1488 Move RunInAdminSnapshot to helpers rather than where types are defined
  storage/admin_helpers.go
  storage/admin_helpers_test.go
  storage/admin_storage.go
Labels: cla: yes, cleanup

#1486 Fix more nits - prob. the last one of these PRs for a bit
  docs/merkletree/treetex/main.go
  integration/admin/admin_integration_test.go
  merkle/compact/tree_test.go
  merkle/sparse_merkle_tree_test.go
  quota/mysqlqm/mysql_quota_test.go
  server/cloudspanner_storage_provider.go
  server/log_rpc_server_test.go
  server/map_rpc_server_test.go
  storage/cache/subtree_cache_test.go
  storage/cloudspanner/map_storage.go
  storage/memory/log_storage.go
  storage/mysql/queue.go
  util/clock/timer_test.go
Labels: cla: yes, cleanup

#1490 Fix updateTreeInfo
  storage/cloudspanner/admin.go
Labels: cla: yes

#1495 Revert workarounds
  .travis.yml
  testonly/integration/etcd/etcd.go
  util/etcd/client.go
Labels: cla: yes

#1493 Introduce BatchInclusionProof func in sparse_merkle_tree.go
  CHANGELOG.md
  merkle/sparse_merkle_tree.go
  merkle/sparse_merkle_tree_test.go
  server/map_rpc_server.go
Labels: cla: yes

#1496 storage/mysql/queue.go: Properly defer statement close in removeSequencedLeaves
  storage/mysql/queue.go
Labels: cla: yes

#1494 Kill all the integration test jobs in parallel
  integration/functions.sh
Labels: cla: yes

#1502 Add trace spans to main proof_fetcher.go funcs
  server/proof_fetcher.go
Labels: cla: yes

#1504 Fix unhandled err in hstar2.
  merkle/hstar2.go
Labels: cla: yes

#1505 Fix unhandled err in log integration test
  integration/log.go
Labels: cla: yes, cleanup

#1508 Fix unhandled err in commit log signer
  docs/storage/commit_log/signer/signer.go
  docs/storage/commit_log/signer/signer_test.go
  docs/storage/commit_log/signer/types.go
Labels: cla: yes

#1506 Introduce Compact Range data structure
  CHANGELOG.md
  merkle/compact/range.go
  merkle/compact/range_test.go
Labels: cla: yes

#1511 maphammer: remove duplicate banner
  testonly/hammer/maphammer/main.go
Labels: cla: yes

#1513 Fix typo
  merkle/compact/range.go
Labels: cla: yes

#1517 Fix a typo in error message
  server/validate.go
Labels: cla: yes

#1516 Format comments, remove unused/buggy methods
  merkle/compact/tree.go
Labels: cla: yes

#1503 Pre-combine child hashes before hashing [rfc6962 hasher]
  merkle/rfc6962/rfc6962.go
  merkle/rfc6962/rfc6962_test.go
Labels: cla: yes

#1519 Use glog package name verbatim
  merkle/compact/tree.go
Labels: cla: yes

#1515 sequencer: update tree size metric regardless
  log/sequencer.go
Labels: cla: yes

#1520 Create CODEOWNERS file
  CODEOWNERS
Labels: cla: yes

#1529 Just the one the
  merkle/rfc6962/rfc6962.go
Labels: cla: yes

#1528 Don't spam the entire team on each pull request
  CODEOWNERS
Labels: cla: yes

#1507 Make storage.Suffix immutable and share instances for 8 bit values.
  merkle/hstar2.go
  merkle/hstar2_test.go
  merkle/sparse_merkle_tree.go
  storage/cache/map_subtree_cache.go
  storage/cache/subtree_cache.go
  storage/cache/subtree_cache_test.go
  storage/suffix.go
  storage/suffix_test.go
  storage/types.go
  storage/types_test.go
Labels: cla: yes

#1530 api: improve docs for Trillian Log gRPC API
  docs/api.md
  trillian_log_api.pb.go
  trillian_log_api.proto
Labels: cla: yes

#1518 Basic bazel build targets for proto files.
  .gitignore
  .travis.yml
  BUILD.bazel
  WORKSPACE
Labels: cla: yes

#1534 Logic bug
  .travis.yml
  docs/storage/commit_log/signer/signer.go
Labels: bug, cla: yes

#1537 sequencer: Simplify error message generation
  log/sequencer.go
Labels: cla: yes

#1514 Improve error handling in flagsaver.
  client/rpcflags/rpcflags_test.go
  cmd/createtree/main_test.go
  cmd/get_tree_public_key/main_test.go
  cmd/updatetree/main_test.go
  server/mysql_storage_provider_test.go
  util/flagsaver/flagsaver.go
  util/flagsaver/flagsaver_test.go
Labels: cla: yes, cleanup, tests

#1538 Move flagsaver to testonly package tree.
  client/rpcflags/rpcflags_test.go
  cmd/createtree/main_test.go
  cmd/get_tree_public_key/main_test.go
  cmd/updatetree/main_test.go
  server/mysql_storage_provider_test.go
  testonly/flagsaver/flagsaver.go
  testonly/flagsaver/flagsaver_test.go
Labels: cla: yes

#1539 Remove unnecessary type
  storage/testonly/fake_node_reader.go
Labels: cla: yes

#1541 Update sequencer tests comment
  log/sequencer_test.go
Labels: cla: yes

#1540 Delete LogMetadata.GetUnsequencedCounts()
  CHANGELOG.md
  storage/log_storage.go
  storage/memory/log_storage.go
  storage/mock_storage.go
  storage/mysql/log_storage.go
  storage/mysql/log_storage_test.go
Labels: cla: yes

#1543 sequencer: Add golden test for non-perfect tree update
  log/sequencer_test.go
Labels: cla: yes

#1523 sequencer: Use batch API to initialize compact.Tree
  CHANGELOG.md
  log/sequencer.go
  log/sequencer_test.go
  merkle/compact/tree.go
  merkle/compact/tree_test.go
  storage/tree_storage.go
Labels: cla: yes

#1545 compact.Tree: Simplify hashes slice population
  merkle/compact/tree.go
Labels: cla: yes

#1546 Add last_sth_timestamp to log signer
  log/sequencer.go
Labels: cla: yes

#1547 compact.Tree: Load hashes even if tree is perfect
  log/sequencer_test.go
  merkle/compact/tree.go
Labels: cla: yes
