Repository google/trillian, pull requests merged in 2019-03, with the labels that each got.

#1441 Draw perfect subtrees as a single element when they're large
  docs/merkletree/treetex/main.go
Labels: cla: yes

#1445 Fix some meganits
  docs/merkletree/treetex/main.go
Labels: cla: yes

#1444 mapclient: GetLeaves: Verify Indexes Before Sending
  CHANGELOG.md
  client/map_client.go
  client/map_client_test.go
Labels: cla: yes

#1449 Add flag to limit max idle database connections for mysql
  CHANGELOG.md
  server/mysql_storage_provider.go
Labels: cla: yes

#1448 Small subtree cache optimization.
  storage/cache/log_subtree_cache.go
Labels: cla: yes

#1455 Add a codecov repository yaml override for Trillian
  codecov.yml
Labels: cla: yes, tests

#1454 Add support for displaying ranges
  docs/merkletree/treetex/main.go
Labels: cla: yes

#1460 Cleanup a bunch of code inspection warnings.
  client/admin.go
  client/map_verifier.go
  integration/log_integration_test.go
  integration/quota/quota_test.go
  merkle/memory_merkle_tree_test.go
  merkle/merkle_path.go
  quota/cacheqm/cache.go
  quota/etcd/etcdqm/etcdqm_test.go
  quota/etcd/storage/quota_storage_test.go
  server/cloudspanner_storage_provider.go
  server/etcd_quota_provider.go
  server/trillian_log_server/main.go
  server/trillian_log_signer/main.go
  server/trillian_map_server/main.go
  storage/cloudspanner/admin.go
  storage/cloudspanner/log_storage.go
  storage/cloudspanner/tree_storage.go
  storage/mysql/log_storage.go
  storage/mysql/storage_test.go
  storage/mysql/tree_storage.go
  storage/testonly/admin_storage_tester.go
  storage/tree_storage.go
  storage/types.go
  testonly/matchers/atleast.go
  util/clock/timer_test.go
  util/election2/testonly/tests.go
Labels: cla: yes, cleanup

#1461 Fix AddSequencedLeaves comments
  docs/api.md
  storage/log_storage.go
  trillian_log_api.pb.go
  trillian_log_api.proto
Labels: cla: yes

#1358 SetAndVerifyMapLeaves
  client/map_client.go
Labels: cla: yes

#1463 go generate ./...
  quota/etcd/quotapb/quotapb.pb.go
  quota/etcd/quotapb/quotapb.pb.gw.go
  quota/etcd/storagepb/storagepb.pb.go
  quota/group_string.go
  quota/kind_string.go
  quota/mock_quota.go
  server/mock_log_operation.go
  storage/cache/mock_node_storage.go
  storage/mock_storage.go
  storage/storagepb/storage.pb.go
  testonly/tmock/mock_admin_server.go
  testonly/tmock/mock_log_server.go
  testonly/tmock/mock_map_server.go
  trees/optype_string.go
  trillian_admin_api.pb.go
  trillian_log_api.pb.go
  trillian_log_sequencer_api.pb.go
  trillian_map_api.pb.go
Labels: cla: yes

#1450 Better gRPC error message forwarding
  client/map_client.go
Labels: cla: yes

#1453 Add some additional tests for storage/types.go
  storage/types.go
  storage/types_test.go
Labels: cla: yes, tests

#1425 Support testing against a locally running mysql docker image
  CHANGELOG.md
  storage/testdb/testdb.go
Labels: cla: yes

#1465 Revert "go generate -run=mockgen ./..."
  quota/mock_quota.go
  server/mock_log_operation.go
  storage/cache/mock_node_storage.go
  storage/mock_storage.go
  testonly/tmock/mock_admin_server.go
  testonly/tmock/mock_log_server.go
  testonly/tmock/mock_map_server.go
Labels: cla: yes

#1467 Remove todo regarding lookup table
  storage/types.go
Labels: cla: yes

#1464 Fix rpc unhandled errors if tx.Close() fails
  server/log_rpc_server.go
  server/map_rpc_server.go
Labels: cla: yes, cleanup

#1468 Fix ParseKeyHint test.
  types/logroot.go
  types/logroot_test.go
Labels: cla: yes, tests

#1466 Fix create.sh to use config file provided.
  examples/deployment/kubernetes/README.md
  examples/deployment/kubernetes/create.sh
Labels: cla: yes

#1446 More efficient Equivalent method for storage.NodeID
  storage/types.go
Labels: cla: yes, enhancement

#1462 Remove deprecated signed log root fields
  CHANGELOG.md
  crypto/signer.go
  docs/api.md
  server/log_rpc_server.go
  server/log_rpc_server_test.go
  storage/cloudspanner/log_storage.go
  storage/mysql/log_storage.go
  trillian.pb.go
  trillian.proto
Labels: cla: yes, cleanup

#1469 Bump go version to 1.11 for travis
  .travis.yml
  integration/log_integration_test.sh
  integration/map_integration_test.sh
  scripts/presubmit.sh
Labels: cla: yes

#1458 GetConsistencyProof - reduce roundtrips (for #1443)
  CHANGELOG.md
  client/log_client.go
  docs/api.md
  server/log_rpc_server.go
  server/log_rpc_server_test.go
  trillian_log_api.pb.go
  trillian_log_api.proto
Labels: cla: yes

#1471 Add tests for admin error paths to some RPC methods.
  server/log_rpc_server.go
  server/log_rpc_server_test.go
Labels: cla: yes, tests

#1475 Extend the tests for the InitLog() RPC to include admin server
  server/log_rpc_server.go
  server/log_rpc_server_test.go
Labels: cla: yes

#1474 Update GetLatestSignedLogRoot Documentation
  CHANGELOG.md
  docs/api.md
  trillian_log_api.pb.go
  trillian_log_api.proto
Labels: cla: yes

#1473 go generate -run=mockgen ./...
  quota/mock_quota.go
  server/mock_log_operation.go
  storage/cache/mock_node_storage.go
  storage/mock_storage.go
  testonly/tmock/mock_admin_server.go
  testonly/tmock/mock_log_server.go
  testonly/tmock/mock_map_server.go
Labels: cla: yes

#1459 Validate hashes passed to GetInclusionProofByHash and GetLeavesByHash
  CHANGELOG.md
  server/log_rpc_server.go
  server/log_rpc_server_test.go
  server/validate.go
Labels: cla: yes

#1470 Log when duplicate indices are fetched in the same request.
  server/map_rpc_server.go
Labels: cla: yes

#1479 Added missing CHANGELOG entries since v1.2.1
  CHANGELOG.md
Labels: cla: yes

#1484 Fix CloudSpanner admin.readTrees query
  CHANGELOG.md
  storage/cloudspanner/admin.go
Labels: cla: yes

#1481 Add a flag (mysql tests only) to set the testdb uri
  storage/testdb/testdb.go
Labels: cla: yes

#1447 Update and clarify some NodeID docs.
  storage/types.go
Labels: cla: yes, docs, enhancement

#1485 api: add diagram of serialized log root
  docs/api.md
  trillian.pb.go
  trillian.proto
Labels: cla: yes

#1477 Add map_server to docker-compose.yml
  examples/deployment/docker-compose.yml
  integration/docker_compose_integration_test.sh
Labels: cla: yes

#1487 Update Go in our Docker images to 1.11
  CHANGELOG.md
  examples/deployment/docker/db_client/Dockerfile
  examples/deployment/docker/log_server/Dockerfile
  examples/deployment/docker/log_signer/Dockerfile
  examples/deployment/docker/map_server/Dockerfile
Labels: cla: yes
